# Stolen from #228
# (Updated dependencies and doesn't use set-output anymore)

name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2
            - name: Checkout
              uses: actions/checkout@v4
            - name: Add SHORT_SHA env property with commit short SHA
              run:
                  $GITHUB_SHA | ForEach-Object { $SHORT_SHA = $_.Substring(0, 8) }
                  Add-Content -Path $env:GITHUB_ENV -Value "SHORT_SHA=$SHORT_SHA"
            - name: MSBuild
              run: |
                  Remove-Item -R -Fo -EA SilentlyContinue bin
                  msbuild /t:Reclass_NET:Rebuild /p:Configuration=Release /p:Platform=x64 ReClass.NET.sln
                  msbuild /t:Reclass_NET:Rebuild /p:Configuration=Release /p:Platform=x86 ReClass.NET.sln
            - name: Zip release
              uses: vimtor/action-zip@v1.2
              with:
                  files: bin\Release
                  recursive: true
                  dest: ReClass.NET.zip
            - name: Release
              uses: softprops/action-gh-release@v2.0.4
              with:
                  token: "${{ secrets.GITHUB_TOKEN }}"
                  tag_name: ${{ env.SHORT_SHA }}
                  prerelease: true
                  generate_release_notes: true
                  name: Development build
                  files: ReClass.NET.zip
